"""
clean_and_format.py

Takes a raw, messy vehicle telemetry CSV log (the kind of thing you'd pull
off a CAN-bus / OBD-II data logger) and turns it into clean, structured
JSON "chunks" sized and shaped for LLM ingestion.

Why this matters (and why it's not just "convert CSV to JSON"):

1. Raw sensor logs are dirty. Missing fields, duplicate timestamps, and
   sensor glitches are the norm, not the exception. Feeding that noise
   straight into a prompt wastes tokens and can mislead a model into
   treating garbage readings as meaningful signal.

2. LLMs don't read CSVs well. Column-aligned text with no explicit keys
   forces the model to infer structure. Explicit key/value JSON removes
   that ambiguity and reduces hallucinated field misreads.

3. Context windows are finite. Dumping 500 raw rows into one prompt wastes
   tokens on redundant steady-state data (idling, cruising) that doesn't
   change the story. This script "chunks" data around interesting *events*
   (fault codes, sensor anomalies) with only a short window of surrounding
   context — similar to how you'd prepare data for retrieval-augmented
   generation (RAG) rather than raw context stuffing.

4. Summarized numeric context beats long token-heavy tables. Instead of
   repeating every row, we compute compact rolling statistics (avg/min/max
   RPM, temp trend) around each event, which is both cheaper in tokens and
   easier for an LLM to reason over.

Usage:
    python3 clean_and_format.py

Outputs:
    output/llm_ready_events.json   - structured event chunks, ready to drop
                                      into an LLM prompt or RAG index
    output/cleaning_report.json    - a log of every data-quality issue found
                                      and how it was handled (for auditability)
"""

import csv
import json
import statistics
from datetime import datetime


RAW_LOG_PATH = "data/raw_vehicle_log.csv"
EVENTS_OUTPUT_PATH = "output/llm_ready_events.json"
REPORT_OUTPUT_PATH = "output/cleaning_report.json"

# How many rows of context to include before/after each fault event when
# building an LLM-ready chunk. Keeps chunks small and relevant instead of
# dumping the entire log into a prompt.
CONTEXT_WINDOW = 5


def load_raw_rows(path):
    with open(path, newline="") as f:
        reader = csv.DictReader(f)
        return list(reader)


def clean_rows(rows):
    """Clean the raw log and return (clean_rows, issues_log).

    Handles the messiness generated by generate_sample_log.py, representative
    of what a real logger export looks like:
      - missing numeric fields      -> forward-filled from the last good reading
      - duplicate timestamps        -> de-duplicated, keeping the first occurrence
      - out-of-range sensor spikes  -> flagged and excluded from numeric stats
      - inconsistent DTC formatting -> trimmed and normalized to uppercase
    """
    issues = []
    cleaned = []
    seen_timestamps = set()
    last_good = {}

    # Reasonable physical bounds for each sensor; anything outside this is
    # treated as a sensor glitch, not a real reading.
    bounds = {
        "rpm": (500, 8000),
        "throttle_pct": (0, 100),
        "coolant_temp_f": (32, 260),
        "vehicle_speed_mph": (0, 200),
    }

    for i, row in enumerate(rows):
        ts = row["timestamp"]

        if ts in seen_timestamps:
            issues.append({
                "row_index": i,
                "issue": "duplicate_timestamp",
                "detail": f"Timestamp {ts} already seen; row skipped.",
            })
            continue
        seen_timestamps.add(ts)

        clean_row = {"timestamp": ts}

        for field, (lo, hi) in bounds.items():
            raw_val = row.get(field, "").strip()

            if raw_val == "":
                # Missing value -> forward-fill
                filled = last_good.get(field)
                issues.append({
                    "row_index": i,
                    "issue": "missing_value",
                    "field": field,
                    "detail": f"Missing {field}; forward-filled with {filled}.",
                })
                clean_row[field] = filled
                continue

            val = float(raw_val)

            if not (lo <= val <= hi):
                # Out-of-range spike -> forward-fill instead of trusting the glitch
                filled = last_good.get(field, val)
                issues.append({
                    "row_index": i,
                    "issue": "out_of_range_value",
                    "field": field,
                    "detail": f"{field}={val} outside plausible range [{lo}, {hi}]; "
                              f"replaced with last good value {filled}.",
                })
                clean_row[field] = filled
                continue

            clean_row[field] = val
            last_good[field] = val

        # Normalize DTC formatting: strip whitespace, force uppercase, treat
        # empty string as "no code" (None) rather than the literal ""
        raw_code = row.get("dtc_code", "").strip().upper()
        if raw_code != row.get("dtc_code", ""):
            issues.append({
                "row_index": i,
                "issue": "malformed_dtc_code",
                "detail": f"DTC code normalized from {row.get('dtc_code')!r} to {raw_code!r}.",
            })
        clean_row["dtc_code"] = raw_code if raw_code else None

        cleaned.append(clean_row)

    return cleaned, issues


def summarize_window(rows):
    """Compute compact rolling statistics for a window of rows, instead of
    passing every raw row to the LLM."""
    def stats(field):
        vals = [r[field] for r in rows if r.get(field) is not None]
        if not vals:
            return None
        return {
            "avg": round(statistics.mean(vals), 1),
            "min": round(min(vals), 1),
            "max": round(max(vals), 1),
        }

    return {
        "rpm": stats("rpm"),
        "throttle_pct": stats("throttle_pct"),
        "coolant_temp_f": stats("coolant_temp_f"),
        "vehicle_speed_mph": stats("vehicle_speed_mph"),
    }


def build_llm_ready_events(cleaned_rows):
    """Find fault-code events and package each one as a small, self-contained
    JSON chunk: the event itself, a summary of sensor behavior just before
    and after it, and a plain-language description an LLM can reason over
    directly without needing the full log."""
    events = []

    for i, row in enumerate(cleaned_rows):
        if not row["dtc_code"]:
            continue

        start = max(0, i - CONTEXT_WINDOW)
        end = min(len(cleaned_rows), i + CONTEXT_WINDOW + 1)
        window = cleaned_rows[start:end]
        before = cleaned_rows[start:i]
        after = cleaned_rows[i + 1:end]

        chunk = {
            "event_type": "diagnostic_trouble_code",
            "dtc_code": row["dtc_code"],
            "timestamp": row["timestamp"],
            "reading_at_event": {
                "rpm": row["rpm"],
                "throttle_pct": row["throttle_pct"],
                "coolant_temp_f": row["coolant_temp_f"],
                "vehicle_speed_mph": row["vehicle_speed_mph"],
            },
            "context_window_seconds": CONTEXT_WINDOW,
            "sensor_summary_before_event": summarize_window(before) if before else None,
            "sensor_summary_after_event": summarize_window(after) if after else None,
            # A short natural-language description makes this chunk usable
            # on its own inside a prompt, without needing extra instructions
            # to explain what the numbers mean.
            "description": (
                f"Fault code {row['dtc_code']} triggered at {row['timestamp']}. "
                f"At the moment of the event: RPM={row['rpm']}, "
                f"throttle={row['throttle_pct']}%, "
                f"coolant temp={row['coolant_temp_f']}F, "
                f"speed={row['vehicle_speed_mph']} mph."
            ),
        }
        events.append(chunk)

    return events


def main():
    raw_rows = load_raw_rows(RAW_LOG_PATH)
    cleaned_rows, issues = clean_rows(raw_rows)
    events = build_llm_ready_events(cleaned_rows)

    with open(EVENTS_OUTPUT_PATH, "w") as f:
        json.dump(events, f, indent=2)

    report = {
        "generated_at": datetime.now().isoformat(),
        "raw_row_count": len(raw_rows),
        "clean_row_count": len(cleaned_rows),
        "issues_found": len(issues),
        "issues": issues,
        "events_extracted": len(events),
    }
    with open(REPORT_OUTPUT_PATH, "w") as f:
        json.dump(report, f, indent=2)

    print(f"Cleaned {len(raw_rows)} raw rows -> {len(cleaned_rows)} clean rows "
          f"({len(issues)} issues fixed).")
    print(f"Extracted {len(events)} LLM-ready event chunks -> {EVENTS_OUTPUT_PATH}")
    print(f"Full cleaning report -> {REPORT_OUTPUT_PATH}")


if __name__ == "__main__":
    main()
